spring:
  application:
    name: pass-web
  datasource:                           # docker-compose? ???? DB ?? ?????.
    url: jdbc:mysql://localhost:3306/batch_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
    username: woojoo
    password: Woojoo0425@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  thymeleaf:
    cache: false